import React from 'react'
import "./style.css"
function Main() {
  return (
    <div className='main-section'>
        <h1>This is main section </h1>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum repudiandae culpa placeat ipsa. Repellendus temporibus quibusdam quod incidunt voluptate architecto, illo dignissimos, perspiciatis perferendis iure expedita voluptatum itaque nisi, quo animi aperiam consectetur. Fugit suscipit aliquam illum. Illum at ex dolore laborum cum atque numquam et aut nostrum vero, aliquid quaerat omnis ullam ducimus reiciendis optio illo odio non reprehenderit soluta? Cum architecto repellat quasi dolore voluptate tempore fuga molestias quo consequuntur nesciunt? Asperiores tempore eius aspernatur modi quae aliquid, ipsa possimus culpa fugit repellendus accusamus laborum nobis! Cupiditate, expedita qui voluptatem quis, reprehenderit possimus repudiandae vitae tempore quidem recusandae, necessitatibus nam ipsum labore. Possimus fugit repudiandae voluptate. Alias, at inventore cumque numquam sapiente aliquid molestiae qui nisi, possimus quia corporis ullam aut optio sint suscipit saepe, et dignissimos nostrum! Suscipit accusantium earum, sunt explicabo, dolorum reiciendis aperiam aliquam saepe possimus cum commodi blanditiis aut esse quas vel libero provident enim doloribus dolorem ex nemo veritatis voluptatibus. Amet quos officiis nam repellendus provident, quod saepe ipsum ut at vero consectetur atque sint cum sequi eum quibusdam porro iure tempore, reiciendis voluptas. Quaerat inventore distinctio nulla nam expedita reiciendis at, dicta blanditiis, maiores doloribus libero porro? Ratione necessitatibus labore autem assumenda.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum repudiandae culpa placeat ipsa. Repellendus temporibus quibusdam quod incidunt voluptate architecto, illo dignissimos, perspiciatis perferendis iure expedita voluptatum itaque nisi, quo animi aperiam consectetur. Fugit suscipit aliquam illum. Illum at ex dolore laborum cum atque numquam et aut nostrum vero, aliquid quaerat omnis ullam ducimus reiciendis optio illo odio non reprehenderit soluta? Cum architecto repellat quasi dolore voluptate tempore fuga molestias quo consequuntur nesciunt? Asperiores tempore eius aspernatur modi quae aliquid, ipsa possimus culpa fugit repellendus accusamus laborum nobis! Cupiditate, expedita qui voluptatem quis, reprehenderit possimus repudiandae vitae tempore quidem recusandae, necessitatibus nam ipsum labore. Possimus fugit repudiandae voluptate. Alias, at inventore cumque numquam sapiente aliquid molestiae qui nisi, possimus quia corporis ullam aut optio sint suscipit saepe, et dignissimos nostrum! Suscipit accusantium earum, sunt explicabo, dolorum reiciendis aperiam aliquam saepe possimus cum commodi blanditiis aut esse quas vel libero provident enim doloribus dolorem ex nemo veritatis voluptatibus. Amet quos officiis nam repellendus provident, quod saepe ipsum ut at vero consectetur atque sint cum sequi eum quibusdam porro iure tempore, reiciendis voluptas. Quaerat inventore distinctio nulla nam expedita reiciendis at, dicta blanditiis, maiores doloribus libero porro? Ratione necessitatibus labore autem assumenda.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum repudiandae culpa placeat ipsa. Repellendus temporibus quibusdam quod incidunt voluptate architecto, illo dignissimos, perspiciatis perferendis iure expedita voluptatum itaque nisi, quo animi aperiam consectetur. Fugit suscipit aliquam illum. Illum at ex dolore laborum cum atque numquam et aut nostrum vero, aliquid quaerat omnis ullam ducimus reiciendis optio illo odio non reprehenderit soluta? Cum architecto repellat quasi dolore voluptate tempore fuga molestias quo consequuntur nesciunt? Asperiores tempore eius aspernatur modi quae aliquid, ipsa possimus culpa fugit repellendus accusamus laborum nobis! Cupiditate, expedita qui voluptatem quis, reprehenderit possimus repudiandae vitae tempore quidem recusandae, necessitatibus nam ipsum labore. Possimus fugit repudiandae voluptate. Alias, at inventore cumque numquam sapiente aliquid molestiae qui nisi, possimus quia corporis ullam aut optio sint suscipit saepe, et dignissimos nostrum! Suscipit accusantium earum, sunt explicabo, dolorum reiciendis aperiam aliquam saepe possimus cum commodi blanditiis aut esse quas vel libero provident enim doloribus dolorem ex nemo veritatis voluptatibus. Amet quos officiis nam repellendus provident, quod saepe ipsum ut at vero consectetur atque sint cum sequi eum quibusdam porro iure tempore, reiciendis voluptas. Quaerat inventore distinctio nulla nam expedita reiciendis at, dicta blanditiis, maiores doloribus libero porro? Ratione necessitatibus labore autem assumenda.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum repudiandae culpa placeat ipsa. Repellendus temporibus quibusdam quod incidunt voluptate architecto, illo dignissimos, perspiciatis perferendis iure expedita voluptatum itaque nisi, quo animi aperiam consectetur. Fugit suscipit aliquam illum. Illum at ex dolore laborum cum atque numquam et aut nostrum vero, aliquid quaerat omnis ullam ducimus reiciendis optio illo odio non reprehenderit soluta? Cum architecto repellat quasi dolore voluptate tempore fuga molestias quo consequuntur nesciunt? Asperiores tempore eius aspernatur modi quae aliquid, ipsa possimus culpa fugit repellendus accusamus laborum nobis! Cupiditate, expedita qui voluptatem quis, reprehenderit possimus repudiandae vitae tempore quidem recusandae, necessitatibus nam ipsum labore. Possimus fugit repudiandae voluptate. Alias, at inventore cumque numquam sapiente aliquid molestiae qui nisi, possimus quia corporis ullam aut optio sint suscipit saepe, et dignissimos nostrum! Suscipit accusantium earum, sunt explicabo, dolorum reiciendis aperiam aliquam saepe possimus cum commodi blanditiis aut esse quas vel libero provident enim doloribus dolorem ex nemo veritatis voluptatibus. Amet quos officiis nam repellendus provident, quod saepe ipsum ut at vero consectetur atque sint cum sequi eum quibusdam porro iure tempore, reiciendis voluptas. Quaerat inventore distinctio nulla nam expedita reiciendis at, dicta blanditiis, maiores doloribus libero porro? Ratione necessitatibus labore autem assumenda.
        </p>
    </div>
  )
}

export default Main